spring.application.name=backend-Ecomm
spring.output.ansi.enabled=ALWAYS


jwt-secret=IshonPandaGoesToCanadaToEarn150KperAnnumAndGetPR
jwt-expiry=86400
jwt-cookie=requestJwtCookie

spring.datasource.url=jdbc:postgresql://localhost:5432/ecomm
spring.datasource.username=postgres
spring.datasource.password=0007


spring.jpa.hibernate.ddl-auto=create-drop

#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecom.backend=DEBUG

project.image=images/




