spring.application.name=backend-Ecomm

jwt-secret=vNDm4HsQ57Oqzt3yi11VZ1E8lE5iFPW4oU+9sQifXAc=
jwt-expiry=86400
jwt-cookie=requestJwtCookie

#spring.datasource.url=jdbc:mysql://localhost:3306/ecomm
#spring.datasource.username=root
#spring.datasource.password=0007


spring.datasource.url=jdbc:postgresql://localhost:5432/ecomm
spring.datasource.username=postgres
spring.datasource.password=0007

#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create



project.image=images/




