spring.application.name=backend-Ecomm

jwt-secret=ishonpandaearns300kDollarPeryearAndLivesInEitherUsOrCanada
jwt-expiry=300
jwt-cookie=requestJwtCookie

#spring.datasource.url=jdbc:mysql://localhost:3306/ecomm
#spring.datasource.username=root
#spring.datasource.password=0007


spring.datasource.url=jdbc:postgresql://localhost:5432/ecomm
spring.datasource.username=postgres
spring.datasource.password=0007

#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update



project.image=images/




